
# General
languageCode: en
title: ChiChi
baseURL: https://chichi.io
enableInlineShortcodes: true

# Markup
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
  tableOfContents:
    startLevel: 2
    endLevel: 6

# Build

buildDrafts: true
buildFuture: true

enableRobotsTXT: true
metadataFormat: yaml
disableKinds:
  - 404
  - taxonomy
  - taxonomyTerm
  - RSS

publichDir: _gh_pages

mediaTypes:
  - text/styl:
      suffixes:
        - styl

  - text/stylus:
      suffixes:
        - styl

# Module

module:
  mounts:
    - source: dist
      target: static/docs/v0.1.0-beta2-alpha1/docs
    - source: site/assets
      target: assets
    - source: site/content
      target: content
    - source: site/data
      target: data
    - source: site/layouts
      target: layouts
    - source: site/static
      target: static
    - source: site/static/docs/v0.1.0-beta2-alpha1/assets/favicons/apple-touch-icon.png
      target: static/apple-touch-icon.png
    - source: site/static/docs/v0.1.0-beta2-alpha1/assets/img/favicons/favicon.ico
      target: static/favicon.ico

# Params
  description: The most popular front-end framework for Stylus
  authors: Jeremy Bolding & ChiChi contributers
  social_image: /docs/v0.1.0-beta2-alpha1/assets/brand/chichi-social.png
  social_logo: /docs/v0.1.0-beta2-alpha1/assets/brand/chichi-social-logo.png

  current_version: 0.1.0-beta2-alpha1
  github_org: https://github.com/chichi
  repo: https://github.com/chichi/chichi
  twitter: chichi-framework
  slack: https://chichi-slack.slack.io
  opencollective: https://opencollective.com/chichi
  blog: https://blog.chichi.io

  download:
    source: https://github.com/chichi-framework/chichi/archive/v0.1.0-beta2-alpha1.zip
    dist: http://github.com/chichi-framework/chichi/releases/download/v0.1.0-beta2-alpha1/chichi-0.1.0-beta2-alpha1-dist.zip

  cdn:
    css: https://cdn.jsdeliver.net/npm/chichi@0.1.0-beta2-alpha1/dist/css/chichi.min.css
    js: https://cdn.jsdeliver.net/npm/chichi@0.1.0-beta2-alpha1/dist/js/chichi.min.js
